### ISSUE TITLE
Creating a ds Composite Test specification Document

### ISSUE THREAD

**Issue by Anbukannadhasan** [rdkcentral/rdk-halif-test-device_settings#10]
Create a ds Composite Test specification document that covers L2, L3 and L4.

**Comment by Ulrond** [comment]
Removed Testing Done -> That's not valid... If this is a testing ticket and theres work to be done, then do the work, report on the ticket, and close the ticket..

It's not a State of either a code change, or something thats in remove, the state is being removed.

Please do something with the ticket either close, it or describe what your actually going todo with it and what the next steps are to move it forward as a task.

**Comment by hari22yuva** [comment]
merged to develop
