### ISSUE TITLE
dsFPD - L2_dsFPD_SetFPstateOFF_SetBrightness - Improper kvp function used to get the number of Indicators

### ISSUE THREAD

**Issue by Anbukannadhasan** [rdkcentral/rdk-halif-test-device_settings#135]
L2_dsFPD_SetFPstateOFF_SetBrightness - To obtain the number of indicators, the straight variable is maintained in the YAML file. It is required to use that variable with the proper KVP function. Currently, the count KVP is used to read the number of indicator variables instead of int32, causing a mismatch and failure.

**Comment by srinivasgtl** [comment]
All changes available in #136 
available in tag 3.1.2
