### ISSUE TITLE
dsVideoDevice : L1 issues for profile reading

### ISSUE THREAD

**Issue by akhilbhas** [rdkcentral/rdk-halif-test-device_settings#141]
* Frame rate in profile is defined as string, and there are some parsing and logical issues identified associated with this.
* Checking of support for API in source or sink device for done before calling the API which causes result check with NOT_SUPPORTED failing in L1
* There are few cases in which NULL is type casted for comparison purposes, this was working in the case of source device but failing for Sink device.

**Comment by hari22yuva** [comment]
merged to develop
