### ISSUE TITLE
L3 C-Test code - device settings - dsDisplay

### ISSUE THREAD

**Issue by akhilbhas** [rdkcentral/rdk-halif-test-device_settings#150]
## Requirement: ##
* Implement functionality-based test interfaces for the dsDisplay Module.
* These Test interfaces can be combined to create a module feature testing.
* The test process document should create different test sequences that can be used to test using the above test interfaces.
* This document should be used for the C-Test Manual validation and also should be useful to automate these test cases using Python scripts under RAFT Framework.

## Acceptance criteria: ##
* Implement all the possible module functionalities for dsDisplay module.
* All these L3 Test functionalities should be part of L3 Test suite.
* The test process document should provide the different test sequences we can person to validate the functionality of this module.

**Comment by hari22yuva** [comment]
merged to develop
