### ISSUE TITLE
L3 C-Test code - device settings - dsCompositeIn

### ISSUE THREAD

**Issue by thanushreevani** [rdkcentral/rdk-halif-test-device_settings#154]
### Implement L3 C-Test code for dsCompositeIn ###
Develop Test Procedure document to describe various test scenarios using C-Test.

### Acceptance criteria: ###
Implement all the possible functionalities on dsCompositeIn module.
Identify External dependency
Create a Test Procedure document that can be used to run the C-Test and to generate the python scripts for RAFT framework and automate the test.

**Comment by hari22yuva** [comment]
merged to develop
