### ISSUE TITLE
UT_ASSERT_EQUAL used to compare string instead of UT_ASSERT_STRING_EQUAL

### ISSUE THREAD

**Issue by akhilbhas** [rdkcentral/rdk-halif-test-device_settings#165]
In device settings Module we have following places UT_ASSERT_EQUAL was used instead of UT_ASSERT_STRING_EQUAL

1. dsAudio
    -  Line 8064:  UT_ASSERT_EQUAL(primaryLanguage, primaryLanguage1); 
    -  Line 8312:  UT_ASSERT_EQUAL(languageCode, languageCode1);
2. dsDisplay
    -  Line  507: UT_ASSERT_EQUAL(edid2->monitorName, edid2->monitorName);
3. dsHdmiIn
    - Line  813: UT_ASSERT_EQUAL(resolution1.name, resolution2.name);

**Comment by hari22yuva** [comment]
merged to develop
