### ISSUE TITLE
dsFPD : Correcting test steps in test_l1_dsFPD_positive_dsFPGetLEDState

### ISSUE THREAD

**Issue by akhilbhas** [rdkcentral/rdk-halif-test-device_settings#184]
In TC test_l1_dsFPD_positive_dsFPGetLEDState, it is calling dsFPSetLEDState with a valid value in step3 after module initialization as below:

// Step 03: Call dsFPSetLEDState() with a valid value
result = dsFPSetLEDState(dsFPD_LED_DEVICE_ACTIVE) 
In step 4, it is getting the same value using dsFPGetLEDState API

// Step 04: Call dsFPGetLEDState() with a valid parameter
result = dsFPGetLEDState(&ledState1); 
and in step5 TC is comparing the value get from dsFPGetLEDState API with a value from profile file.

// Step 05: Compare the retrieved LED state with the expected value from the profile file
UT_ASSERT_KVP_EQUAL_PROFILE_UINT32(ledState1, "dsFPD/SupportedLEDStates"); 

Step 05 is wrong as it is reading All the supported value instead of the current value.

This should be checked with the valid value set in step 3 as follows:

// Step 05: Compare the retrieved LED state with the expected value from the profile file
UT_ASSERT_KVP_EQUAL_PROFILE_UINT32(ledState1, dsFPD_LED_DEVICE_ACTIVE);

**Comment by hari22yuva** [comment]
merged to develop
