### ISSUE TITLE
Makefile upgrade, correcting clean and framework make.

### ISSUE THREAD

**Issue by Ulrond** [rdkcentral/rdk-halif-test-device_settings#192]
Goal:

- clean operation is incorrect and being too aggressive
- making of the framework is incorrect, and it's making the tests as well as the framework.

`make clean` - should perform clean, removing the currently build top level object.
`make cleanall` - should perform clean-all, which destroys framework and lower level objects.

`make clean` - would be expected to be used on a regular basis
`make cleanall` - would be expected to be used very infrequently.

**Comment by hari22yuva** [comment]
merged to develop
