### ISSUE TITLE
L1 - Issue Fix - dsDisapaly 

### ISSUE THREAD

**Issue by akhilbhas** [rdkcentral/rdk-halif-test-device_settings#211]
In test_l1_dsDisplay_positive_dsGetEDID, 

test_l1_dsDisplay_positive_dsGetEDID is failing in positive scenarios as well as the parameter passed to the API is worng.

Currnet VTS code:

    dsDisplayEDID_t *edid1 = {0};
    dsDisplayEDID_t *edid2 = {0}; 

Udpate 
    dsDisplayEDID_t edid1;
    dsDisplayEDID_t edid2;

Call update to 
result = dsGetEDID(displayHandle, &edid1);
result = dsGetEDID(displayHandle, &edid2);

**Comment by hari22yuva** [comment]
merged to develop
