### ISSUE TITLE
VTS L1- dsVideoDevice -IssueFix - SoC Vendor issues.

### ISSUE THREAD

**Issue by akhilbhas** [rdkcentral/rdk-halif-test-device_settings#217]
Fixing Issues reported in 3.1.2
* In the test test_l1_dsVideoDevice_negative_dsSetDFC there are no supported DFCs for the Sink type- Updating the test to reflect the same.
* In test_l1_dsVideoDevice_positive_dsGetVideoCodecInfo bug in source and sink Error check - Fix

**Comment by hari22yuva** [comment]
merged to develop
