### ISSUE TITLE
hal_test binary not created when TARGET=linux is passed to ./build.sh or to make

### ISSUE THREAD

**Issue by kanjoe24** [rdkcentral/rdk-halif-test-device_settings#227]
Observed that hal_test binary is not created while building ut when the command is ./build.sh TARGET=linux or make TARGET=linux. However same works fine w/o TARGET=linux.

The issue is in makefile:(https://github.com/rdkcentral/rdk-halif-test-device_settings/blob/main/Makefile#L32)
```shell
ifeq ($(TARGET),)
$(info TARGET NOT SET )
$(info TARGET FORCED TO Linux)
TARGET=linux
SRC_DIRS += $(ROOT_DIR)/skeletons/src
endif
``` 

This part of the code runs only when TARGET is empty and sets the SRC_DIRS. However when TARGET=linux, SRC_DIRS is not set and hence the error.
[build.sh TARGET=linux.pdf](https://github.com/user-attachments/files/17397226/build.sh.TARGET.linux.pdf)

**Comment by srinivasgtl** [comment]
Changed merged to develop
