### ISSUE TITLE
L1- SoC  - dsAudio

### ISSUE THREAD

**Issue by akhilbhas** [rdkcentral/rdk-halif-test-device_settings#230]
Fix issues found in [3.1.2](https://github.com/rdkcentral/rdk-halif-test-device_settings/milestone/4)

dsGetAudioPort_L1_negative - Fails due to wrong ASSERT usage.
dsSetAudioDelay_L1_positive - Fails due to setAudioDelay for headphone.  As per interface the required delay is set only with HDMI (ARC/eARC) and SPDIF.

**Comment by hari22yuva** [comment]
merged to develop
