### ISSUE TITLE
VTS L1- SoC Vendor Issues - dsHdmiIn : L1 issue

### ISSUE THREAD

**Issue by akhilbhas** [rdkcentral/rdk-halif-test-device_settings#236]
For a sink device or a source device with no HDMI input port, API dsError_t dsHdmiInSelectZoomMode (dsVideoZoom_t requestedZoomMode) is expected to return "NOT_SUPPORTED". The current VTS implementation does not check whether the device type is sink or source to validate the proper return value. So below TC is enabled for both sink and source device, but the TC implementation looks like for source device only, while it expects "NOT_SUPPORTED" for a sink device or a source device that has no input HDMI port.

**Comment by hari22yuva** [comment]
merged to develop
