### ISSUE TITLE
dsDisplay: test_l1_dsDisplay_negative_dsGetDisplayAspectRatio Error checking issue

### ISSUE THREAD

**Issue by Sumip98** [rdkcentral/rdk-halif-test-device_settings#260]
dsGetDisplayAspectRatio is a not-supported API for sink devices.

VTS TC - test_l1_dsDisplay_positive_dsGetDisplayAspectRatio is written to check the return value as dsERR_OPERATION_NOT_SUPPORTED.

But TC test_l1_dsDisplay_negative_dsGetDisplayAspectRatio expects parameter validations for dsGetDisplayAspectRatio API even though it is a not-supported API.

**Comment by akhilbhas** [comment]
Merged to develop
