### ISSUE TITLE
dsFPD: L3: setVerifyLEDIndicator colros test fails for single color LED indicator

### ISSUE THREAD

**Issue by akhilbhas** [rdkcentral/rdk-halif-test-device_settings#270]
### Problem/Opportunity

dsFPD_test04_SetVerifyLEDIndicatorsColor test is failing for the LED indicator which does not support multi color. 

### Steps to reproduce

Run dsFPD_test04_SetVerifyLEDIndicatorsColor.py for indicator which does not support Multicolor.

### Expected Behavior

Test should pas as the Indicator does not support multiple colors

### Actual Behavior

Test fails if the Indicator does not support Multicolor

### Notes (Optional)

Return pass for the test when the test is run for Indicator which does not support multi color.

**Comment by srinivasgtl** [comment]
Merged with develop
