### ISSUE TITLE
Removing DTCP related L1 tests in DS Video Port 

### ISSUE THREAD

**Issue by krishna-1809** [rdkcentral/rdk-halif-test-device_settings#40]
Removing L1 Tests for dsEnableDTCP() and dsIsDTCPEnabled() as these APIs were deprecated in DS Video Port

**Comment by Ulrond** [comment]
@srinivasgtl to review

**Comment by hari22yuva** [comment]
changes are addressed in this PR: https://github.com/rdkcentral/rdk-halif-test-device_settings/pull/90/
