### ISSUE TITLE
Updating the L2 Lowlevel Spec and L2 Test code 

### ISSUE THREAD

**Issue by srinivasgtl** [rdkcentral/rdk-halif-test-device_settings#49]
This task is to update and enhance the L2 low-level design and L2 Test code 

1. This task is to fix the missing documentation issues.
2. Any issues reported during testing.
3. Upgrading the flow diagrams wherever required.

**Comment by mhughesacn** [comment]
Hi Srinivas: I recently asked Comcast Legal about the use of AI-generated code (on foot of a conversation with GeraldW) and their response was: " So, for now, our stance should be that AI-generated code should NOT be submitted to RDK repos."  We (CMF) have requested some more guidance from Legal and expect to update our documents very soon.
- Martin Hughes, RDK CMF Compliance Team

**Comment by Ulrond** [comment]
@srinivasgtl to review

**Comment by srinivasgtl** [comment]
This issue is moved to different PRs and branches creating one PR per module.  There is no need for this issue further.
