### ISSUE TITLE
dsFPD.c : Add Enhanced error code profile check

### ISSUE THREAD

**Issue by akhilbhas** [rdkcentral/rdk-halif-test-device_settings#51]
Add Enhanced error code check from profile for dsFPD.c

**Comment by Sumip98** [comment]
For the Llama panel, the enhanced error is already handled as per the latest spec, so there are further enhanced error code checks to be provided. There is no change in the test suite of dsFPD.

**Comment by hari22yuva** [comment]
merged to develop
