### ISSUE TITLE
VTS L1 Enhancement - Test Profile Changes - Device Setting - Host

### ISSUE THREAD

**Issue by srinivasgtl** [rdkcentral/rdk-halif-test-device_settings#66]
This task is to modify the L1 concerning the latest Test profile changes if any. If there are no changes concerning the test profile, this Jira can be closed with proper information

interface file:
https://github.com/rdkcentral/rdk-halif-device_settings/blob/develop/include/dsHost.h

L1:
https://github.com/rdkcentral/rdk-halif-test-device_settings/blob/develop/src/test_l1_dsHost.c

**Comment by srinivasgtl** [comment]
No changes in the interface file.  No need to address this task.

**Comment by ishthiyaqahmed** [comment]
No changes required as all the API's are getting values from lower lever and we are not setting any values from yaml file.
