### ISSUE TITLE
VTS L1 Enhancement - Header file 3.0.0 updates - Device Setting - host

### ISSUE THREAD

**Issue by srinivasgtl** [rdkcentral/rdk-halif-test-device_settings#85]
This task is to consider the latest header file updates and consider if there are any changes in L1 concerning the newest header files available at tag 3.0.0

**Comment by ishthiyaqahmed** [comment]
since the old and new interface files are same no changes required.

**Comment by srinivasgtl** [comment]
This issue can be considered closed as there are no changes required in this module.
