### ISSUE TITLE
VTS L1 Enhancement - Header file 3.0.0 updates - Device Setting - Display

### ISSUE THREAD

**Issue by srinivasgtl** [rdkcentral/rdk-halif-test-device_settings#86]
This task is to consider the latest header file updates and consider if there are any changes in L1 concerning the newest header files available at tag 3.0.0

**Comment by thanushreevani** [comment]
Compared the display L1 file with https://github.com/rdkcentral/rdk-halif-device_settings/blob/main/include/dsDisplay.h and find no update in interface file. 
So closing this issue
