### ISSUE TITLE
VTS L1 Enhancement - Header file 3.0.0 updates - Device Setting - FP

### ISSUE THREAD

**Issue by srinivasgtl** [rdkcentral/rdk-halif-test-device_settings#89]
This task is to consider the latest header file updates and consider if there are any changes in L1 concerning the newest header files available at tag 3.0.0

**Comment by akhilbhas** [comment]
The issue addressed in PR: https://github.com/rdkcentral/rdk-halif-test-device_settings/pull/92

**Comment by srinivasgtl** [comment]
all changes are now available in tag 3.1.0
